In [18]:
import torch

# 1차원 텐서
a = torch.tensor([1, 2, 3])

# 2차원 텐서
b = torch.tensor([[4, 5, 6]])
b.shape

torch.Size([1, 3])

In [21]:
a.shape

torch.Size([3])

In [22]:
a = a.unsqueeze(1)
a
a.shape

torch.Size([3, 1])

In [23]:
# a + b 연산 수행
c = a + b  # c의 크기: (3, 3)

print(c)

tensor([[5, 6, 7],
        [6, 7, 8],
        [7, 8, 9]])


In [48]:
import torch

day_type = torch.tensor([1, 0, 1, 1, 0])
departure_time = torch.tensor([8.0, 9.5, 11.0, 13.5, 15.0])
busroute_id = torch.tensor([10, 25, 10, 30, 25])
gps_coordx = torch.tensor([37.5665, 37.5410, 37.5550, 37.5125, 37.5330])
gps_coordy = torch.tensor([126.9780, 127.0785, 126.9990, 127.1110, 127.0900])
length = torch.tensor([10.5, 15.2, 8.7, 20.3, 12.6])
day_type

tensor([1, 0, 1, 1, 0])

In [49]:
day_type = day_type.unsqueeze(1)
departure_time = departure_time.unsqueeze(1)
busroute_id = busroute_id.unsqueeze(1)
gps_coordx = gps_coordx.unsqueeze(1)
gps_coordy = gps_coordy.unsqueeze(1)
length = length.unsqueeze(1)
print(day_type)

tensor([[1],
        [0],
        [1],
        [1],
        [0]])


In [50]:
inputs = torch.cat([day_type, departure_time, busroute_id, gps_coordx, gps_coordy, length], dim=1)

print(inputs)

tensor([[  1.0000,   8.0000,  10.0000,  37.5665, 126.9780,  10.5000],
        [  0.0000,   9.5000,  25.0000,  37.5410, 127.0785,  15.2000],
        [  1.0000,  11.0000,  10.0000,  37.5550, 126.9990,   8.7000],
        [  1.0000,  13.5000,  30.0000,  37.5125, 127.1110,  20.3000],
        [  0.0000,  15.0000,  25.0000,  37.5330, 127.0900,  12.6000]])


In [51]:
# 데이터 준비 (리스트의 리스트로 구성)
data_list = [
    [1, 8.0, 10, 37.5665, 126.9780, 10.5, 15],
    [0, 9.5, 25, 37.5410, 127.0785, 15.2, 20],
    [1, 11.0, 10, 37.5550, 126.9990, 8.7, 10],
]

# 가상의 디바이스 함수 (실제 디바이스 이동은 없음)
def to_device(data):
    return f"{data} (on device)"

# 데이터 처리
for i, data in enumerate(data_list):
    # 리스트 컴프리헨션과 to_device 함수 적용
    processed_data = [to_device(d) for d in data]

    # 리스트 unpacking
    day_type, departure_time, busroute_id, gps_coordx, gps_coordy, length, time_gap = processed_data

    # 출력 
    print(f"Sample {i+1}:")
    print(f"  day_type: {day_type}")
    print(f"  departure_time: {departure_time}")
    print(f"  busroute_id: {busroute_id}")
    print(f"  gps_coordx: {gps_coordx}")
    print(f"  gps_coordy: {gps_coordy}")
    print(f"  length: {length}")
    print(f"  time_gap: {time_gap}")
    print()

Sample 1:
  day_type: 1 (on device)
  departure_time: 8.0 (on device)
  busroute_id: 10 (on device)
  gps_coordx: 37.5665 (on device)
  gps_coordy: 126.978 (on device)
  length: 10.5 (on device)
  time_gap: 15 (on device)

Sample 2:
  day_type: 0 (on device)
  departure_time: 9.5 (on device)
  busroute_id: 25 (on device)
  gps_coordx: 37.541 (on device)
  gps_coordy: 127.0785 (on device)
  length: 15.2 (on device)
  time_gap: 20 (on device)

Sample 3:
  day_type: 1 (on device)
  departure_time: 11.0 (on device)
  busroute_id: 10 (on device)
  gps_coordx: 37.555 (on device)
  gps_coordy: 126.999 (on device)
  length: 8.7 (on device)
  time_gap: 10 (on device)



In [1]:

    import time

    start_time = time.strftime("%Y%m%d-%H%M%S")
    # start_time 을 파일명으로 빈 파일 만들어 저장
    with open(f'{start_time}.txt', 'w') as f:
        pass

In [13]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

# LabelEncoder 객체 생성
le = LabelEncoder()

# 예시 데이터
data = ['red', 'green', 'blue', 'red', 'green', 'yellow']

# fit 메서드: 레이블 학습
le.fit(data)
print("학습된 클래스:", le.classes_)
print(le)


학습된 클래스: ['blue' 'green' 'red' 'yellow']
LabelEncoder()


In [14]:
# transform 메서드: 레이블을 숫자로 변환
encoded_data = le.transform(data)
print("인코딩된 데이터:", encoded_data)

인코딩된 데이터: [2 1 0 2 1 3]


In [16]:
# fit_transform 메서드: fit과 transform을 한 번에 수행
encoded_data_2 = le.fit_transform(['apple', 'banana', 'apple', 'cherry'])
print("fit_transform 결과:", encoded_data_2)
print(le.classes_)

fit_transform 결과: [0 1 0 2]
['apple' 'banana' 'cherry']


In [17]:
# inverse_transform 메서드: 숫자를 원래 레이블로 변환
original_labels = le.inverse_transform([0, 1, 2, 0])
print("원래 레이블:", original_labels)

# 새로운 레이블 처리
try:
    le.transform(['purple'])
except ValueError as e:
    print("오류:", str(e))

# 새로운 레이블을 포함하여 다시 학습
le.fit(['red', 'green', 'blue', 'purple'])
print("새로 학습된 클래스:", le.classes_)

# 다차원 배열 처리
multi_dim_data = [['red', 'sweet'], ['green', 'sour'], ['blue', 'sweet']]
le_color = LabelEncoder()
le_taste = LabelEncoder()

encoded_color = le_color.fit_transform([item[0] for item in multi_dim_data])
encoded_taste = le_taste.fit_transform([item[1] for item in multi_dim_data])

print("인코딩된 색상:", encoded_color)
print("인코딩된 맛:", encoded_taste)

원래 레이블: ['apple' 'banana' 'cherry' 'apple']
오류: y contains previously unseen labels: 'purple'
새로 학습된 클래스: ['blue' 'green' 'purple' 'red']
인코딩된 색상: [2 1 0]
인코딩된 맛: [1 0 1]


In [19]:
le_color.classes_

array(['blue', 'green', 'red'], dtype='<U5')

In [20]:
import torch
import torch.nn as nn

# 임베딩 레이어 생성
num_embeddings = 1000  # 어휘 크기
embedding_dim = 50     # 임베딩 차원
embedding_layer = nn.Embedding(num_embeddings=num_embeddings, embedding_dim=embedding_dim)

# 입력 데이터 (예: 단어 인덱스)
input_data = torch.LongTensor([1, 4, 3, 2])

# 임베딩 적용
embedded_data = embedding_layer(input_data)

print("입력 데이터 shape:", input_data.shape)
print("임베딩된 데이터 shape:", embedded_data.shape)

입력 데이터 shape: torch.Size([4])
임베딩된 데이터 shape: torch.Size([4, 50])


In [22]:
print(embedded_data)

tensor([[ 1.1647, -1.4166, -0.6005,  0.2312,  0.4932,  1.2440, -1.3677,  0.9309,
          0.6821, -1.4915, -0.0824, -0.2505,  0.1352,  0.5270,  0.0702,  0.8559,
         -0.5382, -0.5029, -1.0886,  0.3223,  0.6813,  1.2731, -0.4545,  0.2470,
          1.5128,  0.1244,  0.9999, -0.2910, -1.8055,  0.0402, -0.2595, -0.2214,
          0.6948, -1.3050, -0.0240, -1.1019, -0.2661,  1.8513,  2.0974, -1.4183,
         -0.0704, -0.0626, -0.6240, -0.0913, -1.2786, -1.1579, -1.2461, -0.0438,
         -0.2945, -0.4403],
        [ 0.5391,  0.0732, -0.6177, -0.4949, -0.3492, -1.7014, -0.0526,  0.0639,
          1.5922,  2.0719,  1.4767, -0.7027,  0.4149,  2.0745, -0.0865, -1.0116,
          0.1502, -0.9079, -0.8100,  0.2332, -2.9919, -0.5743, -1.1432,  0.5967,
         -0.4597,  0.6448,  0.2451,  0.1534,  1.5803,  0.7931, -0.0529,  0.6083,
         -0.9448, -0.4248,  0.6065, -0.1378,  1.8732, -1.9238, -2.3996,  0.0581,
         -0.4745,  0.3320, -0.6435,  0.2210, -1.1966, -0.0207, -0.5153,  1.3857,


In [23]:
print(input_data)

tensor([1, 4, 3, 2])


In [24]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
import torch
import torch.nn as nn

# 예시 데이터
route_ids = ['10002120', '10003130', '10001110', '10002120', '10003130']

# 1. LabelEncoder를 사용하여 노선 ID를 정수로 변환
le = LabelEncoder()
encoded_routes = le.fit_transform(route_ids)

print("인코딩된 노선 ID:", encoded_routes)

인코딩된 노선 ID: [1 2 0 1 2]


In [2]:
def params_to_string(params):
        return "_".join(f"{k}_{v}" for k, v in params.items())

In [3]:
trial_params = {
        'lr': 1,
        'dropout_rate': 2,
        'batch_size': 3,
        'route_embedding_dim': 4,
        'location_embedding_dim': 5,
        'hash_size': 6
    }

params_to_string(trial_params)

'lr_1_dropout_rate_2_batch_size_3_route_embedding_dim_4_location_embedding_dim_5_hash_size_6'

# 판다스 공백 줄 인식 테스트

In [5]:
import pandas as pd
train_csv = 'dataset/공백제거테스트.csv'
train_data = pd.read_csv(train_csv).dropna(how='all')
# train_data = pd.read_csv(train_csv, skipinitialspace=True).dropna(how='all')

train_data

DAY_TYPE  BUSROUTE_ID  LOCATION_ID DEP_TIME  DEP_TIME1  TIME_GAP  DTCNT 
0         1    100100091    100000032    00:01          0        59      16
1         1    100100091    100000033    00:00          0        28       9
2         1    100100091    100000106    00:04          0        87      26
3         1    100100091    100000107    00:03          0        17      26
4         1    100100091    100000330    00:00          0        28      30